save(auto.calc, file = "autocalcolo smote.Rda")
save(countries_lista, file = "countries large list.Rda")
save(count_table_tot, file = "count_table_tot.Rda")
save(parametri_smote, file = "parametri_smote.Rda")
save(train, file = "original data training set.Rda")
save(validation, file = "validation set original.Rda")
save(stati_bilanciati_train, file = "training smote.Rda")
